# Generated by Django 3.0.5 on 2020-05-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='isFavorited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='isPinned',
            field=models.BooleanField(default=False),
        ),
    ]
